name: SDG_env
channels:
  - defaults
  - conda-forge
dependencies:
  - scikit-learn=1.0.2
  - pandas=1.1.3
  - numpy=1.21.5
  - imbalanced-learn=0.7.0 
  - matplotlib=3.5.2
  - sdv=0.14.1
  - openpyxl=3.0.9
  - seaborn=0.11.2